spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        ddl-auto: update
#        show-sql: true
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: example
    initialization-mode: always
    initialize: true
    schema: classpath:/schema.sql
    continue-on-error: true
#server:
#  port: 9999
#logging:
#  level:
#    org.hibernate: DEBUG
